stages:
    - lint
    - test
    - build
    - deploy

# python template
.python:
    image: python:3.9-slim
    before_script:
        - apt-get update -qq
        - apt-get install -qqy
            build-essential
            libpq-dev
            python3-psycopg2
        - pip install --upgrade pip
        - pip install pipenv
        - pipenv requirements --dev > /tmp/requirements.txt
        - pip install -r /tmp/requirements.txt

# lint using autopep8
lint:python:
    extends: .python
    stage: lint
    script:
        - autopep8
            --diff
            --max-line-length 100
            --ignore E402
            --exit-code
            --aggressive
            --aggressive
            --recursive
            wsgi_app

lint:requirements:
    extends: .python
    stage: lint
    script:
      - diff requirements-base.txt /tmp/requirements.txt

# unit test
test:unit:
    extends: .python
    stage: test
    coverage: /TOTAL\s*\d+\s*\d+\s*([\d\.]+)%/
    variables:
        JWT_SECRET_KEY: jwtsecret
        APP_SECRET_KEY: supersecretkey
        ENCRYPTION_SALT: _y4nTJVIyUJ7fkZYm2OnT5AYHYS_2YAq3gGQOSW80sI=
        SQLALCHEMY_TRACK_MODIFICATIONS: "False"
        DATABASE_URL: postgres://wedontneedthathere
    script:
        - nosetests test/**/*Test.py
          --with-coverage
          --cover-package=wsgi_app/
          --cover-html
          --cover-html-dir=coverage
          --cover-erase
          --cover-xml
          --cover-xml-file=junit.xml
    artifacts:
        reports:
            junit:
                junit.xml
        paths:
            - coverage/
            - .coverage

pages:
    stage: deploy
    image: alpine
    script:
        - mv coverage public
    dependencies:
        - test:unit
    artifacts:
        paths:
            - public/
    only:
        - main

build:css:
    image: node
    stage: build
    script:
        - npm install
        - npx tailwindcss -i wsgi_app/static/src/main.tailwind -o wsgi_app/static/css/main.css

    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - wsgi_app/static/
        exclude:
            - wsgi_app/static/src/

sast:
    stage: test
include:
    - template: Security/SAST.gitlab-ci.yml
