stages:
    - test
lint:
    stage: test
    script:
        - echo "pass"
test:unit:
    stage: test
    image: python:3.9-slim
    variables:
        APP_SECRET_KEY: supersecretkey
        ENCRYPTION_SALT: _y4nTJVIyUJ7fkZYm2OnT5AYHYS_2YAq3gGQOSW80sI=
        SQLALCHEMY_TRACK_MODIFICATIONS: "False"
    script:
        - apt-get update -qq
        - apt-get install -qqy
            build-essential
            libpq-dev
            python3-psycopg2
        - pip install -r requirements-dev.txt
        - python wsgi_app/test/run_tests.py
sast:
    stage: test
include:
    - template: Security/SAST.gitlab-ci.yml
